const  express = require( 'express');
const router=express.Router();
const{teacherRegister, forgotPassword, otpVerify,resetOtp, updatePassword, teacherLogin}=require('../controller/AuthController/teacherAuthController')
const{  uploadCourseDetails, getUploadCourses, editCourseDetails,addChapters, confirmCourse, getCategories, getTeacherDetails, getCourses, getTeachetTransaction, editTeacherDetails, changeChapterIndex, getCourseDetails, editCourse, getChapterDetails, editChapterVideo, editChapterTitle, deleteChapter, updateProfilepic, deleteCourse, getTeacherDashboardTransaction, dashCards, editChapterCaption }=require('../controller/teacherController')
const{verify}=require('../middleWare/auth')
//auth
router.post('/register',teacherRegister)
router.post ('/forgot',forgotPassword)
router.post('/otpVerify',otpVerify)
router.post('/resendOtp',resetOtp)
router.post('/updatePassword',updatePassword)
router.post('/login',teacherLogin)
//course&&others
router.post('/uploadCourse/videos',uploadCourseDetails)
router.get('/coursedetails/:courseId',verify,getCourseDetails)
router.get('/uploadCourse/details',verify,getUploadCourses)
router.put('/edititCourseDetails/:id',editCourseDetails)
router.post('/uploadChapters',verify,addChapters)
router.post('/confirmCourse',verify,confirmCourse)
router.get('/getCategories',verify,getCategories)
router.get('/teacherDetails/:id',verify,getTeacherDetails)
router.get('/courses/:id',verify,getCourses)
router.get('/payments/:id',verify,getTeachetTransaction)
router.get('/dashPayments/:id',verify,getTeacherDashboardTransaction)
router.get('/dashCard/:id',verify,dashCards)
router.put('/couseEdit/:courseId',verify,editCourse)
router.put('/editTeacherDetails/:id',verify,editTeacherDetails)
router.put('/changeIndex/:courseId',verify,changeChapterIndex)
router.get('/chapterDetails/:courseId/:chapterIndex',verify,getChapterDetails)
router.put('/editchapterVideo/:courseId/:chapterIndex',verify,editChapterVideo)
router.put('/editchapterTitle/:courseId/:chapterIndex',verify,editChapterTitle)
router.put('/editchapterCaption/:courseId/:chapterIndex',verify,editChapterCaption)
router.delete('/chapterDelete/:courseId/:chapterIndex',verify,deleteChapter)
router.put('/updateProfilePic/:teacherId',verify,updateProfilepic)
router.delete('/deleteCourse/:course_id',verify,deleteCourse)

module.exports = router